sudo: false

language: python

python: 2.7

cache:
  pip: true
  directories:
    - .tox

before_install:
  - pip install codecov

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=pep8

install:
    - pip install -r dev-requirements.txt

script:
  - tox -e $TOXENV

after_success:
  - codecov

notifications:
  email: false

matrix:
  include:
    - env: TOXENV=py35
      addons: {apt: {sources: deadsnakes}, {packages: python3.5}}
