sudo: false

os:
  - linux
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; brew install python; brew install python3; fi

language: python

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=pep8

install:
    - pip install tox coveralls

script:
  - tox -e $TOXENV

after_success:
  - coveralls

notifications:
  email: false

matrix:
  allow_failures:
    - os: osx
