sudo: false
language: python
python:
 - "2.6"
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.6"
 - "pypy"
 - "pypy3"
 - "3.7-dev"

cache:
  pip: true
  directories:
    - .tox

before_install:
  - pip install codecov
  - pip install tox-travis

install:
    - pip install -r requirements_dev.txt

script:
  - tox --skip-missing-interpreters

after_success:
  - codecov

notifications:
  email: false

deploy:
  provider: pypi
  server: https://pypi.python.org/pypi
  distributions: "sdist bdist_wheel"
  user: "pv8"
  password:
    secure: "L7o85k5LaAC88lo9lfpHo4GA42kurgXXtZ2A4cgS/cQqleROjq36x9IEpAkqFwgQBcL1Aj3j11760EwYBv2j5Auf2OqwENIOLfYiW5YiKu9gCt3Xkh+UceAj/CrH3aRM/hwNwePmCY6x9iPtaY8aR0PEuVzaE2lPLIIllhPPQJg="
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
