language: python
python: 3.6

cache:
  pip: true
  directories:
    - .tox

before_install:
  - pip install codecov
  - cd $HOME
  - mkdir -p bin
  - export PATH=$HOME/bin:$PATH
  - "if [[ $TOXENV == 'pypy3' ]]; then deactivate && wget https://bitbucket.org/squeaky/portable-pypy/downloads/pypy3.5-5.7.1-beta-linux_x86_64-portable.tar.bz2 && tar -jxvf pypy3.5-5.7.1-beta-linux_x86_64-portable.tar.bz2 && echo 'Setting up aliases...' && export PATH=$HOME/pypy3.5-5.7.1-beta-linux_x86_64-portable/bin/:$PATH && ln -s ~/pypy3.5-5.7.1-beta-linux_x86_64-portable/bin/pypy3.3 ~/bin/python && echo 'Setting up pip...' && pypy3.5-5.7.1-beta-linux_x86_64-portable/bin/pypy -m ensurepip && ln -s ~/pypy3.5-5.7.1-beta-linux_x86_64-portable/bin/pip3.3 ~/bin/pip ; fi"
  - cd $TRAVIS_BUILD_DIR

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=pep8

install:
    - pip install -r requirements_dev.txt

script:
  - tox --skip-missing-interpreters -e $TOXENV

after_success:
  - codecov

notifications:
  email: false

deploy:
  provider: pypi
  server: https://pypi.python.org/pypi
  distributions: "sdist bdist_wheel"
  user: "pv8"
  password:
    secure: "L7o85k5LaAC88lo9lfpHo4GA42kurgXXtZ2A4cgS/cQqleROjq36x9IEpAkqFwgQBcL1Aj3j11760EwYBv2j5Auf2OqwENIOLfYiW5YiKu9gCt3Xkh+UceAj/CrH3aRM/hwNwePmCY6x9iPtaY8aR0PEuVzaE2lPLIIllhPPQJg="
  on:
    branch: master
    tags: true
    condition: "$TOXENV = py27"
