sudo: false

language: python

python: 2.7

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5

cache:
  pip: true
  directories:
    - .tox

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=pep8

install:
    - pip install -r dev-requirements.txt

script:
  - tox -e $TOXENV

after_success:
  - coveralls

notifications:
  email: false
