language: python
python: 3.5

cache:
  pip: true
  directories:
    - .tox

before_install:
  - pip install codecov

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=pep8

install:
    - pip install -r requirements_dev.txt

script:
  - tox -e $TOXENV

after_success:
  - codecov

notifications:
  email: false
