sudo: false

language: python

python: 2.7

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=pep8

install:
    - pip install -r dev-requirements.txt
    - pip install coveralls

script:
  - tox -e $TOXENV

after_success:
  - coveralls

notifications:
  email: false
